import { useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router';
import { ArrowRight, ShieldCheck } from 'lucide-react';
import { Button, Field, inputCls } from '../../components/ui';
import { Logo } from '../../components/Logo';
import { supabase } from '../../lib/supabase';

export function AdminSignup() {
  const [params] = useSearchParams(); const nav = useNavigate();
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const token = params.get('invite') ?? '';
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!token) return setNotice('An admin invitation link is required.'); setBusy(true); setNotice(''); const { data, error } = await supabase.auth.signUp({ email, password, options: { data: { full_name: name }, emailRedirectTo: `${window.location.origin}/admin/signup?invite=${token}` } }); if (error) setNotice(error.message); else if (data.session) { const { error: inviteError } = await supabase.rpc('accept_admin_invite', { p_token: token }); if (inviteError) setNotice(inviteError.message); else nav('/admin', { replace: true }); } else setNotice('Check your email to confirm your account, then reopen this invitation link.'); setBusy(false); };
  return <div className="grid min-h-screen place-items-center bg-paper px-6 py-12"><div className="w-full max-w-md"><Logo /><div className="mt-10 rounded-2xl border border-line bg-white p-7"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-tekhelet/10 text-tekhelet"><ShieldCheck size={24} /></div><h1 className="mt-5 font-display text-3xl font-bold">Create admin account</h1><p className="mt-2 text-sm text-ink-soft">This is restricted to a valid PICT Robotics Club invitation.</p><form className="mt-6 space-y-4" onSubmit={submit}><Field label="Full name" required><input required value={name} onChange={(e) => setName(e.target.value)} className={inputCls} /></Field><Field label="Invited email" required><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className={inputCls} /></Field><Field label="Password" required><input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className={inputCls} placeholder="At least 8 characters" /></Field>{notice && <p className="rounded-lg bg-paper-2 px-3 py-2 text-sm text-ink-soft">{notice}</p>}<Button variant="cta" size="lg" className="w-full" disabled={busy}>{busy ? 'Creating account…' : 'Create authorized account'} <ArrowRight size={16} /></Button></form><p className="mt-5 text-center text-sm text-ink-soft">Already have access? <Link to="/admin/login" className="font-semibold text-tekhelet">Admin login</Link></p></div></div></div>;
}
